// src/datosHoteles.js

const imagenPlaceholder = "https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=500";

export const hotelesSEO = [
  // ZONA 1
  { slug: 'sjd-to-cabo-azul-resort', nombre: 'Cabo Azul Resort', imagen: imagenPlaceholder },
  { slug: 'sjd-to-viceroy-los-cabos', nombre: 'Viceroy Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-hyatt-ziva-los-cabos', nombre: 'Hyatt Ziva Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-royal-solaris', nombre: 'Royal Solaris', imagen: imagenPlaceholder },
  { slug: 'sjd-to-barcelo-gran-faro', nombre: 'Barceló Gran Faro', imagen: imagenPlaceholder },
  { slug: 'sjd-to-krystal-grand-los-cabos', nombre: 'Krystal Grand Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-holiday-inn-resort', nombre: 'Holiday Inn Resort', imagen: imagenPlaceholder },
  { slug: 'sjd-to-posada-real', nombre: 'Posada Real', imagen: imagenPlaceholder },
  { slug: 'sjd-to-casa-natalia', nombre: 'Casa Natalia', imagen: imagenPlaceholder },
  { slug: 'sjd-to-el-encanto-inn-suites', nombre: 'El Encanto Inn & Suites', imagen: imagenPlaceholder },
  { slug: 'sjd-to-alegranza-luxury-resort', nombre: 'Alegranza Luxury Resort', imagen: imagenPlaceholder },
  { slug: 'sjd-to-las-mananitas', nombre: 'Las Mañanitas', imagen: imagenPlaceholder },
  { slug: 'sjd-to-royal-decameron-los-cabos', nombre: 'Royal Decameron Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-park-royal-homestay-los-cabos', nombre: 'Park Royal Homestay Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-gr-solaris-lighthouse-los-cabos', nombre: 'GR Solaris Lighthouse Los Cabos', imagen: imagenPlaceholder },

  // ZONA 2
  { slug: 'sjd-to-las-ventanas-al-paraiso', nombre: 'Las Ventanas al Paraíso (A Rosewood Resort)', imagen: imagenPlaceholder },
  { slug: 'sjd-to-one-and-only-palmilla', nombre: 'One&Only Palmilla', imagen: imagenPlaceholder },
  { slug: 'sjd-to-grand-velas-los-cabos', nombre: 'Grand Velas Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-chileno-bay-resort', nombre: 'Chileno Bay Resort & Residences', imagen: imagenPlaceholder },
  { slug: 'sjd-to-le-blanc-spa-resort', nombre: 'Le Blanc Spa Resort', imagen: imagenPlaceholder },
  { slug: 'sjd-to-marquis-los-cabos', nombre: 'Marquis Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-hilton-los-cabos', nombre: 'Hilton Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-dreams-los-cabos', nombre: 'Dreams Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-garza-blanca-resort', nombre: 'Garza Blanca Resort', imagen: imagenPlaceholder },
  { slug: 'sjd-to-casa-del-mar-zoetry', nombre: 'Casa del Mar / Zoëtry', imagen: imagenPlaceholder },
  { slug: 'sjd-to-mar-del-cabo', nombre: 'Mar del Cabo', imagen: imagenPlaceholder },
  { slug: 'sjd-to-las-residencias-golf-beach-club', nombre: 'Las Residencias Golf & Beach Club', imagen: imagenPlaceholder },
  { slug: 'sjd-to-zadun-ritz-carlton-reserve', nombre: 'Zadún (A Ritz-Carlton Reserve)', imagen: imagenPlaceholder },
  { slug: 'sjd-to-jw-marriott-los-cabos-beach-resort', nombre: 'JW Marriott Los Cabos Beach Resort & Spa', imagen: imagenPlaceholder },
  { slug: 'sjd-to-secrets-puerto-los-cabos-golf-spa', nombre: 'Secrets Puerto Los Cabos Golf & Spa Resort', imagen: imagenPlaceholder },
  { slug: 'sjd-to-hotel-el-ganzo', nombre: 'Hotel El Ganzo', imagen: imagenPlaceholder },
  { slug: 'sjd-to-paradisus', nombre: 'Paradisus', imagen: imagenPlaceholder },

  // ZONA 3
  { slug: 'sjd-to-park-hyatt-los-cabos-cabo-del-sol', nombre: 'Park Hyatt Los Cabos at Cabo del Sol', imagen: imagenPlaceholder },
  { slug: 'sjd-to-villas-de-cabo-del-sol', nombre: 'Villas de Cabo del Sol', imagen: imagenPlaceholder },
  { slug: 'sjd-to-grand-fiesta-americana', nombre: 'Grand Fiesta Americana', imagen: imagenPlaceholder },
  { slug: 'sjd-to-breathless-cabo-san-lucas', nombre: 'Breathless Cabo San Lucas Resort & Spa', imagen: imagenPlaceholder },
  { slug: 'sjd-to-corazon-cabo-resort', nombre: 'Corazón Cabo Resort & Spa', imagen: imagenPlaceholder },
  { slug: 'sjd-to-me-cabo', nombre: 'ME Cabo', imagen: imagenPlaceholder },
  { slug: 'sjd-to-pueblo-bonito-blanco', nombre: 'Pueblo Bonito Blanco (Los Cabos Beach Resort)', imagen: imagenPlaceholder },
  { slug: 'sjd-to-marina-fiesta-resort', nombre: 'Marina Fiesta Resort & Spa', imagen: imagenPlaceholder },
  { slug: 'sjd-to-playa-grande-resort', nombre: 'Playa Grande Resort', imagen: imagenPlaceholder },
  { slug: 'sjd-to-bahia-hotel-beach-house', nombre: 'Bahía Hotel & Beach House', imagen: imagenPlaceholder },
  { slug: 'sjd-to-los-milagros-hotel', nombre: 'Los Milagros Hotel', imagen: imagenPlaceholder },
  { slug: 'sjd-to-the-bungalows-hotel', nombre: 'The Bungalows Hotel', imagen: imagenPlaceholder },
  { slug: 'sjd-to-cabo-vista-hotel', nombre: 'Cabo Vista Hotel', imagen: imagenPlaceholder },
  { slug: 'sjd-to-siesta-suites', nombre: 'Siesta Suites', imagen: imagenPlaceholder },
  { slug: 'sjd-to-montage-los-cabos', nombre: 'Montage Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-riu-palace-cabo-san-lucas', nombre: 'Riu Palace Cabo San Lucas', imagen: imagenPlaceholder },
  { slug: 'sjd-to-riu-palace-baja-california', nombre: 'Riu Palace Baja California', imagen: imagenPlaceholder },
  { slug: 'sjd-to-riu-santa-fe', nombre: 'Riu Santa Fe', imagen: imagenPlaceholder },
  { slug: 'sjd-to-city-express-plus-marriott', nombre: 'City Express Plus by Marriott Cabo San Lucas', imagen: imagenPlaceholder },
  { slug: 'sjd-to-holiday-inn-express-cabo-san-lucas', nombre: 'Holiday Inn Express Cabo San Lucas', imagen: imagenPlaceholder },
  { slug: 'sjd-to-fairfield-inn-marriott-los-cabos', nombre: 'Fairfield Inn by Marriott Los Cabos', imagen: imagenPlaceholder },
  { slug: 'sjd-to-villa-del-arco-beach-resort', nombre: 'Villa del Arco Beach Resort & Spa', imagen: imagenPlaceholder },
  { slug: 'sjd-to-villa-del-palmar-beach-resort', nombre: 'Villa del Palmar Beach Resort & Spa', imagen: imagenPlaceholder },
  { slug: 'sjd-to-villa-la-estancia-beach-resort', nombre: 'Villa La Estancia Beach Resort & Spa', imagen: imagenPlaceholder },
  { slug: 'sjd-to-el-tezal', nombre: 'El Tezal', imagen: imagenPlaceholder },
  { slug: 'sjd-to-villas-del-tezal', nombre: 'Villas del Tezal', imagen: imagenPlaceholder },
  { slug: 'sjd-to-casas-de-pedregal', nombre: 'Casas de Pedregal', imagen: imagenPlaceholder },
  { slug: 'sjd-to-villas-de-pedregal', nombre: 'Villas de Pedregal', imagen: imagenPlaceholder },
  { slug: 'sjd-to-the-cape-a-thompson-hotel', nombre: 'The Cape, a Thompson Hotel', imagen: imagenPlaceholder },
  { slug: 'sjd-to-misiones-del-cabo', nombre: 'Misiones del Cabo', imagen: imagenPlaceholder },
  { slug: 'sjd-to-cabo-bello', nombre: 'Cabo Bello', imagen: imagenPlaceholder },
  { slug: 'sjd-to-villas-de-cabo-bello', nombre: 'Villas de Cabo Bello', imagen: imagenPlaceholder },
  { slug: 'sjd-to-sirena-del-mar-hyatt', nombre: 'Sirena del Mar (Hyatt Vacation Club)', imagen: imagenPlaceholder },
  { slug: 'sjd-to-esperanza-auberge-resorts', nombre: 'Esperanza, Auberge Resorts Collection', imagen: imagenPlaceholder },
  { slug: 'sjd-to-hacienda-encantada-resort', nombre: 'Hacienda Encantada Resort & Residences', imagen: imagenPlaceholder },
  { slug: 'sjd-to-vista-encantada-spa-resort', nombre: 'Vista Encantada Spa Resort & Residences', imagen: imagenPlaceholder },
  { slug: 'sjd-to-villas-de-hacienda-encantada', nombre: 'Villas de Hacienda Encantada', imagen: imagenPlaceholder },
  { slug: 'sjd-to-hacienda-del-mar-los-cabos-resort', nombre: 'Hacienda del Mar Los Cabos Resort', imagen: imagenPlaceholder }
];